language: cpp

complier: 
    - clang

before_install: 
    - git clone https://github.com/coderguang/Common.git
    - mv Common ../
    
  
script:
  - cd server/s_select
  - make clean && make
  - cd server/s_poll
  - make clean && make
  - cd server/s_epoll
  - make clean && make
  