language: cpp

complier: 
    - clang

before_install: 
    - git clone https://github.com/coderguang/Common.git
    - cd Common/include/json/
    - make clean && make
    - cd ../../../
    - cd Common/lib/
    - rm -rf *.a
    - cd ../../
    - cd Common/log/
    - make clean && make
    - cd ../../
    - cd Common/util/
    - make clean && make
    - cd ../../
    - cd Common/net/socket/
    - make clean && make
    - cd ../../../
    - mv Common ../
    
  
script:
  - cd server/s_select
  - make clean && make
  - cd ../
  - cd s_poll
  - make clean && make
  - cd ../
  - cd s_epoll
  - make clean && make
  